### ISSUE TITLE
Why does vanilla include build steps

### ISSUE THREAD

**Issue by evanplaice** [open-wc/example-vanilla#1]
If this is the base for an actual vanilla web component. I'd assume that means it doesn't require build steps to work.

That means:
- the WC and it's dependencies are importable via ESM
- the WC code works natively in supported browsers
- it uses the native Shadow DOM

This could be simplified by removing the build steps for vue, lit-html, and webpack. AFAICT, all 3 should be unnecessary.

**Comment by daKmoR** [comment]
hey,

yes this is/was the output of the `scaffold-vanilla` generator... however we didn't apply/update the update of all the generator changes we did... so this actually does not reflect the latest state anymore 🙈 

you will get a way more update to date version if you run the generator yourself...

would you recommend to delete this repo? or do you think it's worth it to make a script that automatically updates it every week or so?

**Comment by evanplaice** [comment]
Oh, cool. As a consumer, it's useful to see what the actual output of the generator looks like ahead of time. As a maintainer, if it's a pain to keep it regularly up-to-date I'd delete it.

Will it be possible to choose what gets added via Yeoman in the future? Ex I'm not a huge fan of mocha/chai or bloating the root of a project with tooling configs (ex editorconfig) but would love to use this for stuff like storybook, and using karma to compile down to ES5 for legacy support.

**Comment by daKmoR** [comment]
We may need to do the same for the starter-app so if we can do it for one we can do it for two :p so let's see how that goes 🙈 

Regarding the generators they are split into small pieces you can pick an choose some guidance is here https://open-wc.org/developing/generator.html#available-upgrade-generators

**Comment by evanplaice** [comment]
Cool. I'll try adding stuff piecemeal. I'll close this since it's pretty much a non-issue. Thanks.
